package com.myapp.learningtube.domain.transcript.dto;

import com.myapp.learningtube.domain.transcript.TranscriptSourceType;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.Instant;

@Schema(description = "자막 트랙 메타(목록·선택 뷰)")
public class TranscriptTrackSummaryResponse {

    @Schema(description = "트랙 ID", example = "9")
    private Long trackId;

    @Schema(description = "공용 Video ID", example = "12")
    private Long videoId;

    @Schema(description = "BCP47 유사 언어 코드", example = "ko")
    private String languageCode;

    @Schema(description = "자동 생성 자막 여부")
    private boolean autoGenerated;

    @Schema(description = "출처")
    private TranscriptSourceType source;

    @Schema(description = "현재 영상에서 사용자에게 적용 중인 트랙 여부")
    private boolean selected;

    @Schema(description = "세그먼트 수(목록 API에서만 채움; 상세 뷰에서는 선택적)")
    private Long segmentCount;

    @Schema(description = "갱신 시각")
    private Instant updatedAt;

    public Long getTrackId() {
        return trackId;
    }

    public void setTrackId(Long trackId) {
        this.trackId = trackId;
    }

    public Long getVideoId() {
        return videoId;
    }

    public void setVideoId(Long videoId) {
        this.videoId = videoId;
    }

    public String getLanguageCode() {
        return languageCode;
    }

    public void setLanguageCode(String languageCode) {
        this.languageCode = languageCode;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public TranscriptSourceType getSource() {
        return source;
    }

    public void setSource(TranscriptSourceType source) {
        this.source = source;
    }

    public boolean isSelected() {
        return selected;
    }

    public void setSelected(boolean selected) {
        this.selected = selected;
    }

    public Long getSegmentCount() {
        return segmentCount;
    }

    public void setSegmentCount(Long segmentCount) {
        this.segmentCount = segmentCount;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Instant updatedAt) {
        this.updatedAt = updatedAt;
    }
}
