package com.myapp.learningtube.domain.transcript;

import com.myapp.learningtube.domain.common.BaseEntity;
import com.myapp.learningtube.domain.video.Video;
import jakarta.persistence.Access;
import jakarta.persistence.AccessType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.Index;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import org.hibernate.annotations.OnDelete;
import org.hibernate.annotations.OnDeleteAction;

/**
 * 공용 Video당 여러 언어·자동/수동 트랙. 동일 Video에 대해 {@code selected=true}는 서비스 레벨에서 최대 1개 유지.
 */
@Entity
@Access(AccessType.FIELD)
@Table(
        name = "transcript_tracks",
        uniqueConstraints =
                @UniqueConstraint(
                        name = "uk_transcript_tracks_video_lang_auto",
                        columnNames = {"video_id", "language_code", "is_auto_generated"}),
        indexes = {
            @Index(name = "idx_transcript_tracks_video_selected", columnList = "video_id,selected"),
        })
public class TranscriptTrack extends BaseEntity {

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @OnDelete(action = OnDeleteAction.CASCADE)
    @JoinColumn(name = "video_id", nullable = false)
    private Video video;

    @Column(name = "language_code", nullable = false, length = 16)
    private String languageCode;

    @Column(name = "is_auto_generated", nullable = false)
    private boolean autoGenerated;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 32)
    private TranscriptSourceType source = TranscriptSourceType.YOUTUBE_AUTO;

    /** 동일 Video에서 사용자에게 보여 줄 활성 트랙(단일 선택). */
    @Column(nullable = false)
    private boolean selected;

    protected TranscriptTrack() {}

    public TranscriptTrack(
            Video video, String languageCode, boolean autoGenerated, TranscriptSourceType source, boolean selected) {
        this.video = video;
        this.languageCode = languageCode;
        this.autoGenerated = autoGenerated;
        this.source = source != null ? source : TranscriptSourceType.YOUTUBE_AUTO;
        this.selected = selected;
    }

    public Video getVideo() {
        return video;
    }

    public String getLanguageCode() {
        return languageCode;
    }

    public void setLanguageCode(String languageCode) {
        this.languageCode = languageCode;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public TranscriptSourceType getSource() {
        return source;
    }

    public void setSource(TranscriptSourceType source) {
        this.source = source != null ? source : TranscriptSourceType.YOUTUBE_AUTO;
    }

    public boolean isSelected() {
        return selected;
    }

    public void setSelected(boolean selected) {
        this.selected = selected;
    }
}
