package com.myapp.learningtube.domain.transcript;

import java.util.List;
import java.util.Optional;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

public interface TranscriptTrackRepository extends JpaRepository<TranscriptTrack, Long> {

    List<TranscriptTrack> findByVideo_IdOrderBySelectedDescLanguageCodeAscIdAsc(Long videoId);

    Optional<TranscriptTrack> findByIdAndVideo_Id(Long id, Long videoId);

    Optional<TranscriptTrack> findByVideo_IdAndSelectedTrue(Long videoId);

    Optional<TranscriptTrack> findByVideo_IdAndLanguageCodeAndAutoGenerated(
            Long videoId, String languageCode, boolean autoGenerated);

    @Query("SELECT COUNT(t) FROM TranscriptTrack t WHERE t.video.id = :videoId")
    long countByVideoId(@Param("videoId") Long videoId);
}
