package com.myapp.learningtube.domain.transcript;

import com.myapp.learningtube.domain.transcript.dto.TranscriptSegmentResponse;
import com.myapp.learningtube.domain.transcript.dto.TranscriptTrackSummaryResponse;

public final class TranscriptDtoMapper {

    private TranscriptDtoMapper() {}

    public static TranscriptTrackSummaryResponse toTrackSummary(TranscriptTrack track, Long segmentCount) {
        TranscriptTrackSummaryResponse r = new TranscriptTrackSummaryResponse();
        r.setTrackId(track.getId());
        r.setVideoId(track.getVideo().getId());
        r.setLanguageCode(track.getLanguageCode());
        r.setAutoGenerated(track.isAutoGenerated());
        r.setSource(track.getSource());
        r.setSelected(track.isSelected());
        r.setSegmentCount(segmentCount);
        r.setUpdatedAt(track.getUpdatedAt());
        return r;
    }

    public static TranscriptSegmentResponse toSegment(TranscriptSegment s) {
        TranscriptSegmentResponse r = new TranscriptSegmentResponse();
        r.setLineIndex(s.getLineIndex());
        r.setStartSeconds(s.getStartSeconds());
        r.setEndSeconds(s.getEndSeconds());
        r.setText(s.getText());
        return r;
    }
}
