package com.myapp.learningtube.infra.youtube.transcript;

import com.myapp.learningtube.domain.transcript.TranscriptSourceType;
import java.util.List;
import java.util.Objects;

public record FetchedTranscriptTrack(
        String languageCode,
        boolean autoGenerated,
        TranscriptSourceType source,
        List<FetchedTranscriptCue> cues) {

    public FetchedTranscriptTrack {
        Objects.requireNonNull(languageCode, "languageCode");
        if (languageCode.isBlank()) {
            throw new IllegalArgumentException("languageCode required");
        }
        cues = cues == null ? List.of() : List.copyOf(cues);
        source = source == null ? TranscriptSourceType.YOUTUBE_AUTO : source;
    }
}
